#!/usr/bin/env python3
import re
import sys

TOKEN_SPECIFICATION = [
    ("HEXNUMBER",   r'0x[0-9A-Fa-f]+'),
    ("NUMBER",      r"\d+"),
    ("IDENT",       r"[A-Za-z_][A-Za-z0-9_]*"),
    ("LBRACE",      r"\{"),
    ("RBRACE",      r"\}"),
    ("LBRACK",      r"\["),
    ("RBRACK",      r"\]"),
    ("EQUAL",       r"="),
    ("COMMA",       r","),
    ("SEMI",        r";"),
    ("WS",          r"[ \t]+"),
    ("NEWLINE",     r"\n"),
    ("OTHER",       r".")
]

master_pat = re.compile("|".join(f"(?P<{name}>{pat})" for name, pat in TOKEN_SPECIFICATION))

def tokenize(text):
    line_num = 1
    line_start = 0
    for mo in master_pat.finditer(text):
        kind = mo.lastgroup
        value = mo.group()
        col = mo.start() - line_start + 1
        if kind == "NEWLINE":
            line_num += 1
            line_start = mo.end()
            continue
        if kind == "WS":
            continue
        yield (line_num, col, kind, value)

def preprocess_strip_comments(text):
    # remove // comments
    return re.sub(r"//.*", "", text)

def main(path):
    with open(path, "r", encoding="utf-8") as f:
        text = f.read()
    text = preprocess_strip_comments(text)
    for tok in tokenize(text):
        print(tok)

if __name__ == "__main__":
    path = sys.argv[1] if len(sys.argv) > 1 else "test.cxt"
    main(path)


# How this assembler works:
# Since the cartridge is just free floating memory with a short block of 
# pointer registers at the start, and there are no standard memory layouts
# for code or data.

# While you could define a memory layout manually, this assembler is
# able to assign addresses to code and data automatically, taking note of
# the size of each memory constraint.

# A memory constraint can be 1-65536 bytes in size, and can be referred to
# by name. A specific address can be assigned to a memory constraint (useful
# for fixed hardware registers or following a specific memory map), or it can
# be left unassigned, in which case the assembler will assign it an address
# automatically, starting from 0 and working upwards.

# The assembler will also check for overlapping memory constraints and report
# errors if any are found.

# Memory constraints are defined in a tabular format, starting with a location
# surrounded by square brackets (e.g. [0x0000] or [auto]) followed by the data
# type (e.g. byte, word, byte[16], byte[]), a name, and an optional initializer (e.g. = 0xFF or = {0x01; 0x02; 0x03;}).

# Note for array constraints: if there is no initializer, the size of the array must be specified (e.g. byte[16]). 
# If there is an initializer, the size of the array can be inferred from the number of elements in the initializer (e.g. byte[] = {0x01; 0x02; 0x03;} would create a byte array of size 3).
# This is very useful for defining the program code, as you can just write out the instructions in the initializer and let the assembler figure out how much space they take up.

# top level:
# The top level of the tree that is generated by the parser is a list of memory constraints.
# 