#!/usr/bin/env python3
"""
opgen.py - Extract OP_ enum values from ops.h and write ops.py.

Usage:
    python3 opgen.py [ops.h] [ops.py]

Defaults: ops.h -> ops.py
"""

import re
import sys
from pathlib import Path

def extract_ops(header_text):
    # Grab everything inside the vc_opcode enum body
    m = re.search(r'typedef enum\s*\{([^}]+)\}\s*vc_opcode', header_text, re.DOTALL)
    if not m:
        raise ValueError("Could not find vc_opcode enum in header")

    body = m.group(1)

    ops = {}
    for m in re.finditer(r'\bOP_(\w+)\s*=\s*(0x[0-9A-Fa-f]+|\d+)', body):
        name = m.group(1)       # e.g. PUSH8
        value = int(m.group(2), 0)
        ops[name] = value

    return ops

def write_ops_py(ops, out_path):
    lines = [
        "# Auto-generated by opgen.py",
        "# Source: ops.h (vc_opcode enum)",
        "# Maps opcode mnemonic -> byte value.",
        "",
        "OPCODES: dict[str, int] = {",
    ]

    for name, value in ops.items():
        lines.append(f"    {name!r}: {value:#04x},")

    lines += [
        "}",
        "",
        "# Reverse map: byte value -> mnemonic",
        "OPCODE_NAMES: dict[int, str] = {v: k for k, v in OPCODES.items()}",
        "",
    ]

    Path(out_path).write_text("\n".join(lines))
    print(f"Wrote {len(ops)} opcodes to {out_path}")

def main():
    header = sys.argv[1] if len(sys.argv) > 1 else "ops.h"
    output = sys.argv[2] if len(sys.argv) > 2 else "ops.py"

    text = Path(header).read_text()
    ops = extract_ops(text)
    write_ops_py(ops, output)

if __name__ == "__main__":
    main()